import assert from 'node:assert/strict';
import fs from 'node:fs';
import {reference,total,payable,suggest,rule,issue,validateMonth} from './lib/model';
import {readWorkbook,parseRows} from './lib/importer';
import {createPdf} from './lib/pdf';
assert.equal(reference.rows.length,1250);assert.equal(total(reference.rows),8978.75);assert.equal(total(reference.rows.filter(payable)),8892.75);
for(const [name,n,value] of [['Carol Rocha',286,2057],['Roberta',458,3273],['Val',494,3562.75]] as const){const rr=reference.rows.filter(r=>r.employee===name);assert.equal(rr.length,n);assert.equal(total(rr),value)}
assert.equal(rule('Novo Organizador SOFT INSERT PARANÁ para jogo').value,8);assert.equal(rule('Caixa Organizadora BIG BOX para Card Games').value,9);assert.equal(rule('Kit com 10 Separadores para Caixa Organizadora BIG BOX para Card Games').value,7);assert.equal(rule('Organizador INSERT MDF Terra Mystica BIG BOX Parte 2').value,7);assert.equal(rule('Caixa Organizadora BIG BOX Eldritch Horror Parte 4').value,9);assert.equal(rule('Caixa Organizadora BIG BOX Eldritch Horror Parte 1').value,7);assert.equal(rule('100245 - 3x Dashboard Unitário para Ark Nova').value,5.25);assert.equal(rule('Kit Dashboard para Ark Nova').value,7);assert.equal(suggest('Produto nunca visto').certain,false);
const bytes=fs.readFileSync('C:/Users/helio/Downloads/Fechamento Jira - Agosto 26.xls');const sheets=readWorkbook(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));assert.equal(sheets.length,4);const original=parseRows(sheets[0].rows,'2026-08','teste.xls');assert.equal(total(original.rows),8978.75);assert.equal(original.rows.filter(r=>r.date.startsWith('2026-08')).length,1250);validateMonth(original);
const empty=sheets[0].rows.map((r,i)=>i?[...r.slice(0,1),'',...r.slice(2)]:r);const imported=parseRows(empty,'2026-08','vazio.xls');assert.equal(imported.rows.length,1250);assert(imported.rows.every(r=>r.original===null&&!r.reviewed));const discrepancies=imported.rows.filter((r,i)=>r.value!==reference.rows[i].value);assert(discrepancies.every(r=>!!issue(r)));console.log('Blank import:',discrepancies.length,'ambiguous mismatches, all flagged.');
assert.throws(()=>validateMonth({...original,closed:true}));assert.throws(()=>parseRows([['Resumo','Valor','Prestador (Cola)'],['Produto','abc','Val']],'2026-09','bad.csv'));assert.throws(()=>parseRows([['Resumo','Valor','Prestador (Cola)'],['Produto',7,'']],'2026-09','bad.csv'));
fs.mkdirSync('work/pdf',{recursive:true});for(const name of ['Carol Rocha','Roberta','Val']){const doc=createPdf(reference,name);fs.writeFileSync(`work/pdf/${name}.pdf`,Buffer.from(doc.output('arraybuffer')));console.log(name,doc.getNumberOfPages(),'PDF pages')}
console.log('Reconciliation, import, inference, validation and PDF generation passed.');
