import * as XLSX from 'xlsx';
import {norm,suggest,type Month,type Row} from './model';
export function readWorkbook(bytes:ArrayBuffer){const w=XLSX.read(bytes,{type:'array',cellDates:true});return w.SheetNames.map(name=>({name,rows:XLSX.utils.sheet_to_json<unknown[]>(w.Sheets[name],{header:1,defval:''})}))}
function date(v:unknown){if(v instanceof Date)return v.toISOString().slice(0,10);if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:''}const s=String(v??'').trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:''}
export function parseRows(matrix:unknown[][],month:string,filename:string):Month{
 const h=matrix.findIndex(r=>r.some(c=>norm(String(c))==='resumo'));if(h<0)throw Error('Cabeçalho Resumo não encontrado. Selecione a aba consolidada do Jira.');const heads=matrix[h].map(c=>norm(String(c)));const ix=(s:string)=>heads.findIndex(c=>c.includes(s));const desc=ix('resumo'),employee=ix('prestador (cola)'),dt=ix('data final cola'),order=ix('chave pai'),customer=ix('parent summary'),status=ix('status');if(employee<0)throw Error('Coluna Prestador (Cola) não encontrada.');
 const rows:Row[]=[];for(let i=h+1;i<matrix.length;i++){const r=matrix[i],description=String(r[desc]??'').trim();if(!description||/^(total|subtotal|resumo)$/i.test(description))continue;const raw=r[1],blank=raw===null||raw===undefined||String(raw).trim()==='';let original:number|null=null;if(!blank){const str=String(raw).replace(/R\$/g,'').trim();original=typeof raw==='number'?raw:Number(str.includes(',')?str.replace(/\./g,'').replace(',','.'):str);if(!Number.isFinite(original)||original<0)throw Error(`Valor inválido na linha ${i+1}. Corrija a segunda coluna.`)}const person=String(r[employee]??'').trim();if(!person)throw Error(`Linha ${i+1} sem Prestador (Cola). Preencha a responsável ou Sem Colagem.`);rows.push({id:String(i+1),sourceRow:i+1,description,value:original??suggest(description).value,original,employee:person,date:date(r[dt]),order:String(r[order]??''),customer:String(r[customer]??''),status:String(r[status]??''),reviewed:false,note:''})}
 if(!rows.length)throw Error('Nenhum registro de produção encontrado.');if(rows.length>15000)throw Error('Limite de 15.000 registros por fechamento.');return {month,filename,rows,closed:false,revision:0,updated:''};
}
export function exportSheet(m:Month){const w=XLSX.utils.book_new();const rows=[['Resumo','VALOR','Prestador (Cola)','Data Final Cola','Chave pai','Cliente','Status','Valor original','Revisado','Observação'],...m.rows.map(r=>[r.description,r.value,r.employee,r.date,r.order,r.customer,r.status,r.original,r.reviewed?'Sim':'Não',r.note])];XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet(rows),'Fechamento');XLSX.writeFile(w,`Fechamento-${m.month}.xlsx`)}
